### PR TITLE
Update composer to fix security vulnerabilities

### PR DESCRIPTION
**Pull request by jeremy-portable**

### CODE REVIEW

**Comment by sawks** [comment]
Hi @jeremy-portable - [this commit](https://github.com/PortableStudios/fila-cms/pull/198/commits/81a7d0b9347e42e71c868186b5ad7b5af3609810) is a bunch of formatting changes, not related to composer - is it required?

**Comment by sawks** [comment]
Please do an `npm audit fix` as well, which will update `package-lock.json`

**Comment by jeremy-portable** [comment]
> Hi @jeremy-portable - [this commit](https://github.com/PortableStudios/fila-cms/pull/198/commits/81a7d0b9347e42e71c868186b5ad7b5af3609810) is a bunch of formatting changes, not related to composer - is it required?

Yes, however for some reason, the PHP Composer fails without it. I am also unsure as to why the formatting suddenly got triggered.

**Comment by Nirys** [comment]
> Hi @jeremy-portable - [this commit](https://github.com/PortableStudios/fila-cms/pull/198/commits/81a7d0b9347e42e71c868186b5ad7b5af3609810) is a bunch of formatting changes, not related to composer - is it required?

@sawks / @jeremy-portable , it's because of the linting step.  I'm kinda surprised it's not been a problem before.  It's meant to enforce formatting standards.

**Review by sawks — APPROVED** [review]
Lets look into the linting stuff when we have some time, all good on the package updates

**Pull request merged**
